version: '3'


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
     - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

    networks:
     - laravel
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
    - "4306:3306"
    volumes:
    - mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE: ecomm
       MYSQL_USER: islem
       MYSQL_PASSWORD: 28225822
       MYSQL_ROOT_PASSWORD: 28225822
       SERVICE_TAGS: dev
       SERVICE_NAME: mysql

    networks:
      - laravel
  php:
    build:
     context: .
     dockerfile: DockerFile
     args:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    container_name: php

    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"  

    networks:
      - laravel       






















volumes:
  mysql:
networks:
    laravel:
